services:
  - type: worker
    name: disney-dining-bot
    env: python
    runtime: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: DISNEY_USERNAME
        sync: false
      - key: DISNEY_PASSWORD
        sync: false
    disk:
      name: disney-bot-disk
      mountPath: /app
      sizeGB: 1
